### ISSUE TITLE
MissingSectionHeaderError: File contains no section headers.

### ISSUE THREAD

**Issue by mdelcid13** [collective/collective.spanishdocumentation#5]
Buen día, 
Quisiera solicitarle su apoyo, con Plone 4, hace algún tiempo quiero instalar algunos complementos a mi sitio pero no da resultado. Ahora al querer correr el Buildout da el error: MissingSectionHeaderError: File contains no section headers.

adminplone@plonevm:~/Plone/zinstance$ ./bin/buildout -vN
While:
  Initializing.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/adminplone/Plone/buildout-cache/eggs/zc.buildout-2.2.1-py2.7.egg/zc/buildout/buildout.py", line 1941, in main
    user_defaults, command, args)
  File "/home/adminplone/Plone/buildout-cache/eggs/zc.buildout-2.2.1-py2.7.egg/zc/buildout/buildout.py", line 221, in **init**
    data['buildout'].copy(), override, set()))
  File "/home/adminplone/Plone/buildout-cache/eggs/zc.buildout-2.2.1-py2.7.egg/zc/buildout/buildout.py", line 1558, in _open
    result = zc.buildout.configparser.parse(fp, filename, _default_globals)
  File "/home/adminplone/Plone/buildout-cache/eggs/zc.buildout-2.2.1-py2.7.egg/zc/buildout/configparser.py", line 207, in parse
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: /home/adminplone/Plone/zinstance/buildout.cfg, line: 1
'\xef\xbb\xbf############################################\n'
adminplone@plonevm:~/Plone/zinstance$ 

Alguien que me pueda indicar donde tengo el error o como puedo resolverlo. Gracias.

**Comment by idgserpro** [comment]
@mdelcid13 Check https://github.com/buildout/buildout/issues/245 to see it the workaround solves your problem. In that case, we can close this issue since it isn't actually a collective.spanishdocumentation.
